config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users
  
  root "categories#index"

  resources :categories do
    resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :delete_all 

    validates :category_title , presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :task_title, :task_detail , presence: true
  # validates :completed, inclusion: [true, false]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_category_id, only: [:show, :edit, :update, :destroy]

    def index
        @categories = current_user.categories
    end

    def show
        @tasks = @category.tasks

        @today_events = @tasks.where("due_date = ?", Date.current)
        @after_events = @tasks.where("due_date > ?", Date.current)
        @before_events = @tasks.where("due_date < ?", Date.current)

    end
    
    def new
        @category = Category.new
    end

    def create
        @category = current_user.categories.build(category_params)

        if @category.save
            redirect_to categories_path, notice: 'Category was successfully created'
        else
            render :new
        end
    end

    def edit 
    end

    def update 

        if @category.update(category_params)
            redirect_to categories_path, notice: 'Category was successfully updated'
        else
            render :edit
        end
    end

    def destroy 
        @category.destroy
        redirect_to categories_path, notice: 'Category was successfully deleted'
    end

    private

    def find_category_id
        @category = current_user.categories.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:category_detail, :category_title)
    end
    

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :find_task_id, only: [:create,:update,:destroy ]
    before_action :find_category_task_id, only: [:edit, :show]

    def create     
       @task = @category.tasks.build(task_params)

       if @task.save
            redirect_to category_path(@category), notice: 'Task was successfully created'
        else
            redirect_to category_path(@category), notice: 'Task creation was unsuccessful'
        end
    end

    def show
    end

    def edit     
    end

    def update
        @task = @category.tasks.find(params[:id])

        if @task.update(task_params)
            redirect_to category_path(@category), notice: 'Task was successfully updated'
        else
            render :edit
        end
    end

    def destroy
        @category.tasks.find(params[:id]).destroy
        redirect_to category_path(@category), notice: 'Task was successfully deleted'

    end

    private

    def find_category_task_id
        @category = current_user.categories.find(params[:id])
        @task = @category.tasks.find(params[:category_id])
    end

    def find_task_id
        @category = current_user.categories.find(params[:category_id])
    end

    def task_params
        params.require(:task).permit(:task_title, :task_detail, :due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_flash.html.erb

<% flash.each do |type, msg| %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/categories/_form.html.erb

<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-4 border rounded-1">
      <%= form_with model: @category do |form| %>
     
        <% @category.errors.full_messages.each do |msg|%>
          <div class="alert alert-primary alert-dismissible fade show" role="alert">
            <%= msg %>
          </div>
        <% end %>
     
       <p>
          <div class="form-floating">
          <%= form.text_field :category_title, class:"form-control", placeholder: "Add Title Here" %>
          <%= form.label :category_title, class: "form-label" %>
          </div>
        </p>
        <p>
         <div class="form-floating">
          <%= form.text_area :category_detail, class:"form-control", placeholder: "Write something...", style: "height: 150px;"  %>
          <%= form.label :category_detail, class: "form-label"%>
          </div>
        </p>
        <p>
          <%= form.submit "Submit", class: 'btn btn-primary' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb

<div class="container d-flex justify-content-center mt-5">
    <div class="row">
        <div class="col"><h1>You are Editing a Category!</h1></div>
    </div>
</div>
<%= render "form" %>


app/views/categories/index.html.erb

<div class="container">
    <%= render "flash" %>
</div>

<div class="container mt-2 d-flex justify-content-between ">
<h2>Taskly, task for your dai-ly needs</h2>
<%= link_to "Create New Task Category!", new_category_path, class:"btn btn-primary me-5 align-self-center"%>
</div>

<div class="container my-4">
    <% if @categories.length > 0 %>
        <div class="row">
        <% @categories.each do |category| %>
            <div class="col-4">
            <div class="card mb-3" style="max-width: 25rem; min-height: 20rem;">
            <div class="card-body">
            <h5 class="card-title h1"><%= category.category_title %></h5>
            <p class="card-text lead"><%= category.category_detail.length > 150 ? category.category_detail[0...150]... : category.category_detail == '' ? "No details..." : category.category_detail%></p>
            </div>
            <div class="card-footer d-flex justify-content-between">
            <a class="btn btn-primary position-relative" data-method="get" href="/categories/<%= category.id %>"><i class="bi bi-eye"></i>-SHOW
                <% if category.tasks.where("due_date = ?", Date.current).length > 0 %>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                  <%= category.tasks.where("due_date = ?", Date.current).length %>
                  <span class="visually-hidden">unread messages</span>
                </span>
                <% end %>
            </a>
            <a class="btn btn-primary" data-method="get" href="/categories/<%= category.id %>/edit"><i class="bi bi-pencil-square"></i>-EDIT</a>
            <a data-confirm="Are you sure?" class="btn btn-danger" rel="nofollow" data-method="delete" href="/categories/<%= category.id %>"><i class="bi bi-trash3"></i>-DELETE</a>

            </div> 
            </div> 
            </div>
        <% end %>
    <% else %>
    <h1 class="text-center my-5"><%= image_tag "cow", class: "rounded mx-auto d-block w-50" %>No records Found</h1>
    <% end %>
   
</div>




app/views/categories/new.html.erb

<div class="container d-flex justify-content-center mt-5">
    <div class="row">
        <div class="col"><h1>You are Creating a New Category!</h1></div>
    </div>
</div>
<%= render "form" %>

app/views/categories/show.html.erb
<div class="container">
    <%= render "flash" %>
</div>

<div class="container mt-5 text-center">
    <h1><%= @category.category_title %></h1>
    <div class="row d-flex justify-content-center">
        <div class="col-6"><h3 class="lead"><%= @category.category_detail %></h3></div>
    </div>
</div>
 
<div class="container my-2">
<div class="row text-center justify-content-center">
    <div class="col-6"><h2>Tasks</h2></div>
    <div class="col-6">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          Add Task
        </button>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Info
        </button>
    </div>
</div>
    <div class="row d-flex justify-content-center mt-4">
    <% if @tasks.length > 0 %>
    <% @tasks.where("due_date = ?", Date.current).each do |task| %>
      <%= render "partials/tasks", task: task %>
    <% end %> 
    <% @tasks.where("due_date != ?", Date.current).each do |task| %>
      <%= render "partials/tasks", task: task %>
    <% end %>  
    <% @tasks.where(due_date: nil).each do |task| %>
      <%= render "partials/tasks", task: task %>
    <% end %>  
        </div>
    </div>
</div>

    <% else %>
    <h1 class="text-center "><%= image_tag "todo_working", class: "rounded mx-auto d-block w-25" %>No Tasks Yet</h1>
    <% end %>

<%= render "partials/modals" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous" defer></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>
  <%= render "partials/navbar" %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_modals.html.erb
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Add a Task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "tasks/form" %>
      </div>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Due Date Legend</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul class="list-group text-center">

          <li class="list-group-item">Task Deadline has passed <span class="position-absolute top-0 start-100 translate-middle p-2 bg-warning border border-light rounded-circle">
                    <span class="visually-hidden">New alerts</span>
                </span></li>
          <li class="list-group-item">Task Deadline has yet to pass <span class="position-absolute top-0 start-100 translate-middle p-2 bg-primary border border-light rounded-circle">
                    <span class="visually-hidden">New alerts</span>
                </span></li>
          <li class="list-group-item">Task Deadline is today <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
                    <span class="visually-hidden">New alerts</span>
                </span></li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand mx-3" href="<%= root_path %>"><i class="bi bi-pen"></i> Taskly</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
   <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
       <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        </ul>
      <div class="d-flex">
       
        <% if user_signed_in? %>   
        
         <a class="navbar-brand me-5" href="#">A lovely day, <span class="fw-semibold   "><%= current_user.email %></span></a>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-info mx-1"%>
        <% else %>
        <%= button_to "Sign In", new_user_session_path, method: :get, class: "btn btn-outline-success mx-1" %>
        <%= button_to "Sign Up", new_user_registration_path, method: :get, class: "btn btn-outline-info mx-1" %>
    
        <% end %>
      </div>
    </div>
  </div>
</nav>


    

    

app/views/partials/_tasks.html.erb
 <div class="col-8 ">
        <div class="accordion" id="accordionPanelsStayOpenExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-heading<%=task.id%>">
              <button class="accordion-button position-relative" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse<%=task.id%>" aria-expanded="true" aria-controls="panelsStayOpen-collapse<%=task.id%>">
              <div class="container">
              <div class="row ">
              <div class="col-9"><h5><%= task.task_title %></h5></div>
              <div class="col"><%= link_to '<i class="bi bi-eye"></i>'.html_safe, category_task_path(task.id), class: "btn btn-primary", title: "show"  %>
                <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_category_task_path(task.id), class: "btn btn-primary mx-2", title: "edit"  %>
                <%= link_to '<i class="bi bi-trash3"></i>'.html_safe, [task.category, task],
              method: :delete,
              data: { confirm: "Are you sure?" }, class: "btn btn-danger", title: "delete" %></div></div>
              </div>
                <% if @today_events.where(id: task.id).length > 0 %>
                <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
                    <span class="visually-hidden">New alerts</span>
                </span>
                <% elsif @before_events.where(id: task.id).length > 0 %>
                <span class="position-absolute top-0 start-100 translate-middle p-2 bg-primary border border-light rounded-circle">
                    <span class="visually-hidden">New alerts</span>
                </span>
                <% elsif @after_events.where(id: task.id).length > 0 %>
                <span class="position-absolute top-0 start-100 translate-middle p-2 bg-warning border border-light rounded-circle">
                    <span class="visually-hidden">New alerts</span>
                </span>
                <% end %>
              </button>
            </h2>
            <div id="panelsStayOpen-collapse<%=task.id%>" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-heading<%=task.id%>">
              <div class="accordion-body">
                
                <p class="lead"><%= task.task_detail %></p>
                
                
                <% if task.due_date %>
                <div class="text-muted">Due: <%= task.due_date.strftime("%B %d, %Y") %></div>
                <% end %>
              </div>
            </div>
            </div>
          </div>
        </div>

app/views/tasks/_form.html.erb
<%= form_with model: [ @category, @category.tasks.build ] do |form| %>

  <% @category.errors.full_messages.each do |msg|%>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <%= msg %>
    </div>
  <% end %>
  <p>
    <div class="form-floating">
    <%= form.text_field :task_title, class:"form-control", placeholder: "Add Title Here" %>
    <%= form.label :task_title, class: "form-label" %>
    </div>
  </p>
  <p>
   <div class="form-floating">
    <%= form.text_area :task_detail, class:"form-control", placeholder: "Do chores..." %>
    <%= form.label :task_detail, class: "form-label" %>
    </div>
  </p>
  <p>
    <%= form.label :due_date, class: "form-label" %>
    <%= form.date_field :due_date, class:"form-control" %>
  </p>
  <p>
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/tasks/edit.html.erb

<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-4 border rounded-1">
      <h1>Edit Task</h1>
      <%= form_with model: [ @category , @category.tasks.find(params[:category_id]) ] do |form| %>
       <p>
          <div class="form-floating">
          <%= form.text_field :task_title, class:"form-control", placeholder: "Add Title Here" %>
          <%= form.label :task_title, class: "form-label" %>
          </div>
        </p>
        <p>
         <div class="form-floating">
          <%= form.text_area :task_detail, class:"form-control", placeholder: "Do chores..." %>
          <%= form.label :task_detail, class: "form-label" %>
          </div>
        </p>
        <p>
          <%= form.label :due_date, class: "form-label" %>
          <%= form.date_field :due_date, class:"form-control" %>
        </p>
        <p>
          <%= form.submit "Edit", class: 'btn btn-primary' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-6">
    <h1 class="display-4 mb-3 mt-2"><%= @task.task_title %></h1>
    <h2 class="lead">Detail: <%= @task.task_detail %></h2>
    <p class="text-muted">Deadline: <%= @task.due_date %></p>
    <%= link_to "Back", category_path(@category), class:"btn btn-primary" %>

    </div>
  </div>
</div>





